Added new option `label` in `autoprogram` directive.
sphinx-contrib/autoprogram pull request #7
Opened 2020-01-09 21:30 UTC by Paebbels

This adds an optional label (anchor) to each auto documented program.

**Usage:**

```rest
.. autoprogram::
   :label: <myLabel>
```

**Inserted reST:**

```rest
.. _<myLabel>:<title>:
```

The label can be referenced with :ref:`labelName` in reST.

Solves #6.

2020-01-19 14:36 UTC, Paebbels commented
Any response please?

----------------
The following part in your shell code fails on Travis:

```bash
if git show --format=%B --quiet "${TRAVIS_PULL_REQUEST_SHA:-${TRAVIS_TAG:-${TRAVIS_COMMIT}}}" \
   | grep '\[changelog skip\]' > /dev/null; then
  echo "Skip changelog checker..."
elif [[ "$TRAVIS_TAG" != "" ]]; then
  ! grep -i "to be released" CHANGES.rst
else
  [[ "$TRAVIS_COMMIT_RANGE" = "" ]] || \
  [[ "$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep doc/changelog\.rst)" != "" ]]
fi
```

2020-01-19 20:31 UTC, Paebbels commented
@dahlia does this command check if I modified the change log?

Normally, I would like to get some response first before finishing a PR with all details like change log messages, translation, documentation, etc.

Especially, in the community around Sphinx I get a lot of RP rejects :(. That's why I waited if the PR is considered a good idea, so I can go on in finalizing the PR.

2020-01-19 20:31 UTC, Paebbels commented
@dahlia does this command check if I modified the change log?

Normally, I would like to get some response first before finishing a PR with all details like change log messages, translation, documentation, etc.

Especially, in the community around Sphinx I get a lot of RP rejects :(. That's why I waited if the PR is considered a good idea, so I can go on in finalizing the PR.

2020-01-19 20:48 UTC, Paebbels commented
@dahlia I pushed a change to the `changelog.rst` and also added a snippet in the documentation.

2020-01-19 20:52 UTC, Paebbels commented
Python 2.6 and Python 3.3 is not available on Travis-CI.

![image](https://user-images.githubusercontent.com/956109/72688287-d3a67c00-3b05-11ea-84da-f0408759e9e5.png)

![image](https://user-images.githubusercontent.com/956109/72688300-ec169680-3b05-11ea-9c27-301f2c50279d.png)


Please update the Travis configuration.

2021-02-23 15:28 UTC, brechtm commented
To be consistent with the [standard reStructuredText directives](https://docutils.sourceforge.io/docs/ref/rst/directives.html#common-options), this option should be called `:name:`.

2021-02-23 16:03 UTC, langston-barrett requested changes

2021-06-11 20:33 UTC, closed without merging